[package]
name = "watch_dog"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
log4rs = "1.3.0"
pnet = "0.35.0"
serde = { version = "1.0.206", features = ["derive"] }
sha2 = "0.10.8"
tokio = { version = "1.39.2", features = ["full"] }
toml = "0.8.19"
